# Generated by Django 4.0 on 2021-12-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_admin_user_is_buyer_user_is_supplier'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='session_user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='session_user', to='authentication.user'),
            preserve_default=False,
        ),
    ]
