# Generated by Django 4.0 on 2022-01-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_admin_user_is_buyer_user_is_supplier'),
        ('app', '0003_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_user_season', to='authentication.user')),
            ],
        ),
    ]
